"""0001_core_schema

Revision ID: 82c2c01f10a1
Revises: 
Create Date: 2026-08-21 08:59:14.276450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82c2c01f10a1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=32), server_default='ACTIVE', nullable=False),
    sa.Column('system_role', sa.String(length=32), server_default='USER', nullable=False),
    sa.Column('failed_login_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('must_change_password', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('ACTIVE', 'INACTIVE', 'LOCKED', 'WITHDRAWN')", name=op.f('ck_users_user_status')),
    sa.CheckConstraint("system_role IN ('SYSTEM_ADMIN', 'USER')", name=op.f('ck_users_user_system_role')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('workspaces',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('allow_llm', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('allow_web_search', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("type IN ('PERSONAL', 'TEAM')", name=op.f('ck_workspaces_workspace_type')),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_workspaces_owner_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workspaces'))
    )
    op.create_index('ix_workspaces_owner_id', 'workspaces', ['owner_id'], unique=False)
    op.create_index('uq_workspaces_one_personal_per_owner', 'workspaces', ['owner_id'], unique=True, postgresql_where=sa.text("type = 'PERSONAL' AND deleted_at IS NULL"))
    op.create_table('tags',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('color', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_tags_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tags')),
    sa.UniqueConstraint('workspace_id', 'name', name='uq_tags_workspace_name')
    )
    op.create_index('ix_tags_workspace_id', 'tags', ['workspace_id'], unique=False)
    op.create_table('workspace_categories',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_workspace_categories_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workspace_categories')),
    sa.UniqueConstraint('workspace_id', 'slug', name='uq_workspace_categories_workspace_slug')
    )
    op.create_index('ix_workspace_categories_workspace_id', 'workspace_categories', ['workspace_id'], unique=False)
    op.create_table('workspace_members',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=32), server_default='MEMBER', nullable=False),
    sa.Column('status', sa.String(length=32), server_default='ACTIVE', nullable=False),
    sa.Column('invited_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('ADMIN', 'MEMBER', 'VIEWER')", name=op.f('ck_workspace_members_workspace_member_role')),
    sa.CheckConstraint("status IN ('PENDING', 'ACTIVE', 'INACTIVE')", name=op.f('ck_workspace_members_workspace_member_status')),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], name=op.f('fk_workspace_members_invited_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_workspace_members_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_workspace_members_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workspace_members')),
    sa.UniqueConstraint('workspace_id', 'user_id', name='uq_workspace_members_workspace_user')
    )
    op.create_index('ix_workspace_members_user_id', 'workspace_members', ['user_id'], unique=False)
    op.create_index('ix_workspace_members_workspace_id', 'workspace_members', ['workspace_id'], unique=False)
    op.create_table('workspace_stages',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_default', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_terminal', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_workspace_stages_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workspace_stages')),
    sa.UniqueConstraint('workspace_id', 'slug', name='uq_workspace_stages_workspace_slug')
    )
    op.create_index('ix_workspace_stages_workspace_id', 'workspace_stages', ['workspace_id'], unique=False)
    op.create_table('ideas',
    sa.Column('idea_code', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('one_line_definition', sa.String(length=500), nullable=True),
    sa.Column('original_text', sa.Text(), nullable=True),
    sa.Column('background', sa.Text(), nullable=True),
    sa.Column('problem', sa.Text(), nullable=True),
    sa.Column('core_concept', sa.Text(), nullable=True),
    sa.Column('major_features', sa.Text(), nullable=True),
    sa.Column('expected_effect', sa.Text(), nullable=True),
    sa.Column('target_users', sa.Text(), nullable=True),
    sa.Column('scenarios', sa.Text(), nullable=True),
    sa.Column('challenges', sa.Text(), nullable=True),
    sa.Column('minimum_validation', sa.Text(), nullable=True),
    sa.Column('related_project', sa.Text(), nullable=True),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('stage_id', sa.UUID(), nullable=False),
    sa.Column('priority', sa.String(length=32), server_default='MEDIUM', nullable=False),
    sa.Column('feasibility', sa.String(length=32), server_default='UNKNOWN', nullable=False),
    sa.Column('visibility', sa.String(length=32), server_default='WORKSPACE', nullable=False),
    sa.Column('assignee_id', sa.UUID(), nullable=True),
    sa.Column('next_review_date', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("feasibility IN ('HIGH', 'MEDIUM', 'LOW', 'UNKNOWN')", name=op.f('ck_ideas_idea_feasibility')),
    sa.CheckConstraint("priority IN ('HIGH', 'MEDIUM', 'LOW')", name=op.f('ck_ideas_idea_priority')),
    sa.CheckConstraint("visibility IN ('PRIVATE', 'WORKSPACE', 'SELECTED_USERS')", name=op.f('ck_ideas_idea_visibility')),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], name=op.f('fk_ideas_assignee_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_ideas_author_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['category_id'], ['workspace_categories.id'], name=op.f('fk_ideas_category_id_workspace_categories'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['stage_id'], ['workspace_stages.id'], name=op.f('fk_ideas_stage_id_workspace_stages'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_ideas_workspace_id_workspaces'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ideas')),
    sa.UniqueConstraint('workspace_id', 'idea_code', name='uq_ideas_workspace_idea_code')
    )
    op.create_index('ix_ideas_author_id', 'ideas', ['author_id'], unique=False)
    op.create_index('ix_ideas_category_id', 'ideas', ['category_id'], unique=False)
    op.create_index('ix_ideas_next_review_date', 'ideas', ['next_review_date'], unique=False)
    op.create_index('ix_ideas_stage_id', 'ideas', ['stage_id'], unique=False)
    op.create_index('ix_ideas_workspace_id', 'ideas', ['workspace_id'], unique=False)
    op.create_index('ix_ideas_workspace_stage_id', 'ideas', ['workspace_id', 'stage_id'], unique=False)
    op.create_index('ix_ideas_workspace_updated_at', 'ideas', ['workspace_id', 'updated_at'], unique=False)
    op.create_table('idea_participants',
    sa.Column('idea_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['idea_id'], ['ideas.id'], name=op.f('fk_idea_participants_idea_id_ideas'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_idea_participants_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('idea_id', 'user_id', name=op.f('pk_idea_participants')),
    sa.UniqueConstraint('idea_id', 'user_id', name='uq_idea_participants_idea_user')
    )
    op.create_index('ix_idea_participants_idea_id', 'idea_participants', ['idea_id'], unique=False)
    op.create_index('ix_idea_participants_user_id', 'idea_participants', ['user_id'], unique=False)
    op.create_table('idea_shares',
    sa.Column('idea_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('permission', sa.String(length=32), server_default='READ', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint("permission IN ('READ', 'EDIT')", name=op.f('ck_idea_shares_idea_share_permission')),
    sa.ForeignKeyConstraint(['idea_id'], ['ideas.id'], name=op.f('fk_idea_shares_idea_id_ideas'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_idea_shares_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_idea_shares')),
    sa.UniqueConstraint('idea_id', 'user_id', name='uq_idea_shares_idea_user')
    )
    op.create_index('ix_idea_shares_idea_id', 'idea_shares', ['idea_id'], unique=False)
    op.create_index('ix_idea_shares_user_id', 'idea_shares', ['user_id'], unique=False)
    op.create_table('idea_tags',
    sa.Column('idea_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['idea_id'], ['ideas.id'], name=op.f('fk_idea_tags_idea_id_ideas'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('fk_idea_tags_tag_id_tags'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('idea_id', 'tag_id', name=op.f('pk_idea_tags')),
    sa.UniqueConstraint('idea_id', 'tag_id', name='uq_idea_tags_idea_tag')
    )
    op.create_index('ix_idea_tags_idea_id', 'idea_tags', ['idea_id'], unique=False)
    op.create_index('ix_idea_tags_tag_id', 'idea_tags', ['tag_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_idea_tags_tag_id', table_name='idea_tags')
    op.drop_index('ix_idea_tags_idea_id', table_name='idea_tags')
    op.drop_table('idea_tags')
    op.drop_index('ix_idea_shares_user_id', table_name='idea_shares')
    op.drop_index('ix_idea_shares_idea_id', table_name='idea_shares')
    op.drop_table('idea_shares')
    op.drop_index('ix_idea_participants_user_id', table_name='idea_participants')
    op.drop_index('ix_idea_participants_idea_id', table_name='idea_participants')
    op.drop_table('idea_participants')
    op.drop_index('ix_ideas_workspace_updated_at', table_name='ideas')
    op.drop_index('ix_ideas_workspace_stage_id', table_name='ideas')
    op.drop_index('ix_ideas_workspace_id', table_name='ideas')
    op.drop_index('ix_ideas_stage_id', table_name='ideas')
    op.drop_index('ix_ideas_next_review_date', table_name='ideas')
    op.drop_index('ix_ideas_category_id', table_name='ideas')
    op.drop_index('ix_ideas_author_id', table_name='ideas')
    op.drop_table('ideas')
    op.drop_index('ix_workspace_stages_workspace_id', table_name='workspace_stages')
    op.drop_table('workspace_stages')
    op.drop_index('ix_workspace_members_workspace_id', table_name='workspace_members')
    op.drop_index('ix_workspace_members_user_id', table_name='workspace_members')
    op.drop_table('workspace_members')
    op.drop_index('ix_workspace_categories_workspace_id', table_name='workspace_categories')
    op.drop_table('workspace_categories')
    op.drop_index('ix_tags_workspace_id', table_name='tags')
    op.drop_table('tags')
    op.drop_index('uq_workspaces_one_personal_per_owner', table_name='workspaces', postgresql_where=sa.text("type = 'PERSONAL' AND deleted_at IS NULL"))
    op.drop_index('ix_workspaces_owner_id', table_name='workspaces')
    op.drop_table('workspaces')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
