"""Labeled Idea corpus for search ranking evaluation (Step 25).

Idea codes in titles (e.g. [SR-MEET-01]) are stable labels for ground truth.
"""

from __future__ import annotations

from typing import Any

# Fields map to IdeaCreate / embedding text (one_line_definition, core_concept, …).
SEARCH_RANKING_CORPUS: list[dict[str, Any]] = [
    {
        "code": "SR-MEET-01",
        "title": "[SR-MEET-01] 회의록 자동 정리",
        "one_line_definition": "회의 음성과 노트를 구조화된 회의록으로 자동 정리하는 서비스",
        "problem": "회의 후 회의록 작성이 반복되고 누락이 잦다",
        "core_concept": "STT와 요약으로 회의 내용을 자동 정리",
        "expected_effect": "회의록 작성 시간 단축",
        "tags": ["회의록", "자동화", "미팅"],
        "topic": "meeting",
    },
    {
        "code": "SR-MEET-02",
        "title": "[SR-MEET-02] 미팅 액션아이템 추적",
        "one_line_definition": "회의에서 나온 할 일을 자동 추출하고 담당자에게 알림",
        "problem": "회의 액션아이템이 잊힌다",
        "core_concept": "액션아이템 추출과 리마인더",
        "tags": ["미팅", "할일"],
        "topic": "meeting",
    },
    {
        "code": "SR-MED-WRITE-01",
        "title": "[SR-MED-WRITE-01] 진료 기록 자동 작성 보조",
        "one_line_definition": "의사가 반복해서 작성하는 진료 기록·의료 문서를 AI로 초안 작성",
        "problem": "병원 기록 작성 부담이 크고 진료 시간을 줄인다",
        "core_concept": "음성/템플릿 기반 의무기록 초안 생성",
        "expected_effect": "병원 기록 작성 줄이기",
        "tags": ["병원", "진료", "의료문서", "자동화"],
        "topic": "medical_write",
    },
    {
        "code": "SR-MED-WRITE-02",
        "title": "[SR-MED-WRITE-02] 의료 문서 작성 보조 워크벤치",
        "one_line_definition": "퇴원요약·진단서 등 의료 문서 작성 보조",
        "problem": "의료 문서 서식이 다양하고 수작업이 많다",
        "core_concept": "서식별 문서 작성 보조",
        "tags": ["의료 문서", "병원"],
        "topic": "medical_write",
    },
    {
        "code": "SR-MED-SEARCH-01",
        "title": "[SR-MED-SEARCH-01] 환자 기록 검색",
        "one_line_definition": "과거 의무기록·차트에서 환자 기록을 빠르게 검색",
        "problem": "필요한 환자 기록을 찾기 어렵다",
        "core_concept": "의무기록 전문 검색과 하이라이트",
        "tags": ["환자", "검색", "차트"],
        "topic": "medical_search",
    },
    {
        "code": "SR-INV-01",
        "title": "[SR-INV-01] 재고 부족 사전 알림",
        "one_line_definition": "재고가 떨어지기 전에 알려주는 시스템",
        "problem": "재고 소진을 늦게 알아 결품이 발생한다",
        "core_concept": "임계치 기반 재고 알림과 발주 추천",
        "tags": ["재고", "알림"],
        "topic": "inventory",
    },
    {
        "code": "SR-INV-02",
        "title": "[SR-INV-02] 다창고 재고 통합 대시보드",
        "one_line_definition": "여러 창고의 재고와 이동을 한눈에",
        "problem": "창고별 재고 파악이 분산되어 있다",
        "core_concept": "통합 재고 뷰",
        "tags": ["재고", "창고"],
        "topic": "inventory",
    },
    {
        "code": "SR-OCR-01",
        "title": "[SR-OCR-01] 서류 OCR 자동화",
        "one_line_definition": "스캔 서류에서 문자를 인식해 구조화 데이터로 변환",
        "problem": "종이 서류 입력이 수작업이다",
        "core_concept": "OCR과 필드 매핑 자동화",
        "tags": ["OCR", "자동화"],
        "topic": "ocr",
    },
    {
        "code": "SR-OCR-02",
        "title": "[SR-OCR-02] 영수증 이미지 텍스트 추출",
        "one_line_definition": "영수증 사진에서 금액·가맹점을 OCR로 추출",
        "problem": "경비 영수증 입력이 번거롭다",
        "core_concept": "모바일 영수증 OCR",
        "tags": ["OCR", "경비"],
        "topic": "ocr",
    },
    {
        "code": "SR-AUTO-01",
        "title": "[SR-AUTO-01] 병원 업무 자동화 허브",
        "one_line_definition": "병원 내부 반복 업무를 자동화하는 통합 허브",
        "problem": "병원 업무에 반복 수작업이 많다",
        "core_concept": "워크플로 자동화로 내부 업무 효율화",
        "tags": ["병원", "자동화", "효율화"],
        "topic": "automation",
    },
    {
        "code": "SR-AUTO-02",
        "title": "[SR-AUTO-02] 내부 업무 효율화 봇",
        "one_line_definition": "반복되는 내부 업무를 봇으로 효율화",
        "problem": "내부 업무에 시간이 낭비된다",
        "core_concept": "RPA성 자동화 봇",
        "tags": ["자동화", "내부 업무", "효율화"],
        "topic": "automation",
    },
    {
        "code": "SR-AI-DOC-01",
        "title": "[SR-AI-DOC-01] AI 문서 처리 파이프라인",
        "one_line_definition": "문서를 분류·요약·추출하는 AI 문서 처리",
        "problem": "비정형 문서 처리에 인력이 소요된다",
        "core_concept": "LLM 기반 문서 처리 파이프라인",
        "tags": ["AI 문서", "문서 처리"],
        "topic": "ai_doc",
    },
    {
        "code": "SR-AI-DOC-02",
        "title": "[SR-AI-DOC-02] 계약서 조항 요약",
        "one_line_definition": "계약서 핵심 조항을 AI로 요약",
        "problem": "긴 계약서 리뷰 시간이 길다",
        "core_concept": "조항 추출과 요약",
        "tags": ["문서", "AI"],
        "topic": "ai_doc",
    },
    {
        "code": "SR-CRM-01",
        "title": "[SR-CRM-01] 영업 파이프라인 CRM",
        "one_line_definition": "리드부터 성사까지 고객 관리 CRM",
        "problem": "영업 기회가 스프레드시트에 흩어져 있다",
        "core_concept": "파이프라인 기반 고객 관리",
        "tags": ["CRM", "영업"],
        "topic": "crm",
    },
    {
        "code": "SR-HR-01",
        "title": "[SR-HR-01] 채용 온보딩 체크리스트",
        "one_line_definition": "신규 입사자 온보딩과 채용 절차 자동화",
        "problem": "인사 온보딩 누락이 잦다",
        "core_concept": "HR 체크리스트와 알림",
        "tags": ["인사", "채용", "HR"],
        "topic": "hr",
    },
    {
        "code": "SR-LOG-01",
        "title": "[SR-LOG-01] 라스트마일 배송 최적화",
        "one_line_definition": "도심 배송 경로를 최적화하는 물류 시스템",
        "problem": "배송 지연과 운송비 증가",
        "core_concept": "경로 최적화와 창고 연동",
        "tags": ["물류", "배송"],
        "topic": "logistics",
    },
    {
        "code": "SR-FIN-01",
        "title": "[SR-FIN-01] 경비 정산 자동화",
        "one_line_definition": "직원 경비와 청구서 정산을 자동화",
        "problem": "회계 정산 수작업이 많다",
        "core_concept": "영수증·청구서 기반 정산",
        "tags": ["회계", "정산"],
        "topic": "finance",
    },
    {
        "code": "SR-EDU-01",
        "title": "[SR-EDU-01] 개인화 학습 퀴즈",
        "one_line_definition": "학습자 수준에 맞춘 퀴즈와 커리큘럼",
        "problem": "획일적 강의로 학습 효과가 낮다",
        "core_concept": "적응형 교육 콘텐츠",
        "tags": ["교육", "학습"],
        "topic": "education",
    },
    {
        "code": "SR-RET-01",
        "title": "[SR-RET-01] 매장 고객 동선 분석",
        "one_line_definition": "리테일 매장 내 고객 동선과 프로모션 효과 분석",
        "problem": "매장 진열 효과를 측정하기 어렵다",
        "core_concept": "센서 기반 동선 분석",
        "tags": ["매장", "리테일"],
        "topic": "retail",
    },
    {
        "code": "SR-GEN-01",
        "title": "[SR-GEN-01] 만능 업무 플랫폼",
        "one_line_definition": "모든 업무를 한곳에서 처리하는 범용 서비스 시스템",
        "problem": "도구가 너무 많다",
        "core_concept": "통합 업무 플랫폼",
        "tags": ["플랫폼", "서비스"],
        "topic": "generic",
    },
]
